### PR TITLE
Free implementation of srfi/5

### PR DESCRIPTION
**Pull request by LiberalArtist**
Replace non-free `syntax-rules` implementation of SRFI 5
with a free implementation using `syntax-parse`, which
should also give better error messages.

Add some tests that both the old and new implementations pass.

Deprecate the `srfi-lib-nonfree` package, but retain it
as a stub for backwards compatibility.

### CODE REVIEW

**Comment by LiberalArtist** [comment]
I'd appreciate someone checking that I've done the right things with the package dependencies and `implies` statements, in particular.

**Comment by LiberalArtist** [comment]
In this PR, I only change the docs by using the same message for SRFI 5 as for [SRFI 29](https://docs.racket-lang.org/srfi-nf/srfi-29.html).

I think it would be nice to do more, but I'm not completely settled on what the right thing is or how to implement it in Scribble. Currently, the free `srfi-doc` documentation doesn't even mention the existence of the `srfi-doc-nonfree` docs, which seems confusing, especially since `srfi-doc` reads like it's a comprehensive list of SRFIs in Racket and, before https://github.com/racket/srfi/pull/5, it was.

For people who don't have `srfi-doc-nonfree`, I think the best experience would be for links (especially from right-click > "View documentation for …") to point to a section of the free SRFI Scribble document. We could explain the license for the original spec in prose and resolve the link either to the copy from `srfi-doc-nonfree`, if it's installed, or otherwise to https://docs.racket-lang.org. I think Scribble has the infrastructure to do this, though I haven't yet tried using the [`'indirect-link` style property](https://docs.racket-lang.org/scribble/core.html#(def._((lib._scribble%2Fcore..rkt)._link-element))) with something other than [`seclink`](https://docs.racket-lang.org/scribble/base.html#(def._((lib._scribble%2Fbase..rkt)._seclink))). 

This would be a change, though: currently, "View documentation for …" links try to jump into the original spec. I haven't looked into how they do this, and, at least for SRFI 5, it doesn't seem to work very well right now (i.e. the link goes to a badly-chosen place in the spec). I don't know if this change would bother anyone. It might be more relevant for SRFI 29, which defines multiple bindings.

I think it would also be reasonable to keep things very simple and just link to the versions on https://srfi.schemers.org for these two SRFIs, but that would be an even bigger change.

**Comment by LiberalArtist** [comment]
Related to https://github.com/racket/srfi/issues/4

**Comment by samth** [comment]
This looks good to me.

**Pull request merged**
