### PR TITLE
separate nonfree libs into dedicated subpackage

### PR DESCRIPTION
**Pull request by dbenoit17**
This PR is intended to reduce the impact of restrictively licensed components within `racket/srfi`.  See the following github issue https://github.com/racket/srfi/issues/4.

Currently, package maintainers for GNU/Linux distributions with strict licensing policies must remove the nonfree components from this package before distributing the Racket main distribution.  This brings up the following two concerns:

1)  Extra work is required for package maintainers to manually remove nonfree components for each Racket release.

2)  Distro users are not able to resolve the nonfree components via raco once they are removed by package maintainers.

This PR mitigates both of the above issues with the following changes.

Changelog:
* Add subpackage `srfi-lib-nonfree`
* Move SRFI 5 to `srfi-lib-nonfree`
* Add subpackage `srfi-doc-nonfree`
* Move SRFI 5 and SRFI 29 docs to `srfi-doc-nonfree`
* Update SRFI 32 to latest version which is released under a free license
* Replace short nonfree code excerpt in SRFI 29 with an equivalent free implementation

Notes:
* The SRFI 29 library and documents end up being distributed in separate packages, because its implementation is free while its docs are not.  This decision was made because SRFI 29 is a dependency of SRFI 19, which is itself a dependency of other packages in the main distribution.  SRFI 29 should therefore not be removed by package maintainers along with the nonfree SRFI components.

* I have tested the changes, and they build and work for me as expected.  I did need to add the two new subpackages to links.rktd in order for them to build with the main distribution.

### CODE REVIEW

**Comment by jeapostrophe** [comment]
For the code in `srfi-doc-nonfree/srfi/scribblings/srfi-nf.scrbl` can take the corresponding code from the normal srfi docs, put it in a "util.rkt" file and then require that so we don't have code duplication?

**Comment by dbenoit17** [comment]
Of course, thanks for the suggestion!

**Comment by dbenoit17** [comment]
Should be all set now.

**Comment by jeapostrophe** [comment]
Sorry, but this is a super picky thing, but could you make that util module be `srfi-doc/srfi/scribblings/utils.rkt` (you can then do `(require srfi/scribblings/utils)`. The current name might imply it should be publicly used, but `scribblings` is implicit private.

**Comment by dbenoit17** [comment]
Fixed!

**Comment by jeapostrophe** [comment]
Thank you very much! I'm merging now.

**Pull request merged**
